name: seamless
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - fortran-compiler
  - netcdf-fortran
  - jupyterlab
  - cmake
  - numpy
  - matplotlib
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
  - nco
  - salib
  - pip:
      - parsac
      - https://www.parallelpython.com/downloads/pp/pp-1.6.4.4.zip
