name: seamless-bb
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - fortran-compiler
  - netcdf-fortran
  - jupyterlab
  - cmake
  - numpy
  - matplotlib=3.4.*
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
  - nco
  - salib
  - blas
  - lapack
  - mpi4py
  - pyqt
  - pip:
      - -e ./extern/parsac
      - pyncview
      - https://www.parallelpython.com/downloads/pp/pp-1.6.4.4.zip
