name: seamless
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fortran-compiler
  - netcdf-fortran
  - jupyterlab
  - cmake
  - numpy
  - matplotlib
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
  - nco
  - pip:
      - parsac
