name: Build
on: push
jobs:
   main:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Clone
        uses: actions/checkout@v2
        with:
           submodules: recursive
      - name: Install conda environment
        run: |
          conda env create -f environment.yml
          conda init bash
      - name: Compile
        run: |
          conda activate seamless-bb
          bash ./install
